### PR TITLE
Upgrading falafel to 1.2.0

### PR DESCRIPTION
**Pull request by aa6**

### CODE REVIEW

**Comment by epatpol** [comment]
I guess we'll never see this package updated right? I'm having real trouble finding a decent library that can trace function calls and time spent in each (in node.js)... Any suggestions? (Sorry for the hijack of an old PR btw).

**Comment by aa6** [comment]
Sorry, can't help much. I stopped searching any further after realizing that `njsTrace` was the best I could find for my purposes.
Although it was almost two years ago and things certainly might have changed for now.

**Comment by ValYouW** [comment]
Hey, sorry guys, I totally forgot about it...
I'll do my best to get to it soon, the thing is I am not that familiar with ES6 changes to the AST (like arrow functions).
thx

**Comment by ValYouW** [comment]
@epatpol @aa6  Hi, I have pushed changes on master that supports the latest version of falafel and I've also made changes to support arrow functions... If you want you can give it a shot and see if it works for you...

**Pull request closed without merging**
